version: '2'
services:
  web:
    build: .
    ports:
     - "4200:4200"
    volumes:
     - .:/hospitalrun-frontend
    links:
     - couchdb
    working_dir: /hospitalrun-frontend
    command: make -f Makefile.docker serve
  couchdb:
    image: couchdb:latest
    ports:
     - "5984:5984"
